services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    env_file:
      - .env.docker

  db:
    image: mysql:8.0
    container_name: emiliehedou-db
    env_file:
      - .env.docker
    environment:
      # Obligatoire pour l'initialisation MySQL
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
